name: AWS Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your AWS region

      - name: Build Your Application (Example)
        run: |
          npm install
          npm run build  # Or your build commands (Maven, Python, etc.)

      - name: Deploy to AWS S3 (Example)
        run: |
          aws s3 sync build s3://your-s3-bucket-name --delete

      # Or, if deploying to EC2:
      # - name: Deploy to AWS EC2
      #   run: |
      #     # Replace with your EC2 deployment commands
      #     # (Using AWS CLI, CodeDeploy, etc.)
